### ISSUE TITLE
the module doesnt show up 

### ISSUE THREAD

**Issue by bastos5** [crimsonclyde/mmm-udr#2]
Hello hello, thanks for the module!

Unfotunatly it doesnt show up on my magic mirror.. Do you have an idea?

whats  is a device ID created at amazon? 
moduleName | "" | The device id that you've created at Amazon.

Thanks,
Bastien

**Comment by crimsonclyde** [comment]
Hi bastos5,

please try simple this in you config.js

		{
			module: "mmm-udr",
			position: "bottom_bar"
		}

Just ignore the settings, I need to update this :) asap!

clyde

**Comment by crimsonclyde** [comment]
README.md updated.

**Comment by bastos5** [comment]
Hello, thanks for the answer. there is a problem with majuscule.
Because the dowloaded folder name is MMM-UDR while you said mmm-udr.
Juste change the name folder and it works.

Bastien

**Comment by bastos5** [comment]
hello, the module showed up but it didnt read the calendar.. Also, could it be possible to supress "Nothing special today - enjoy!" and also enlarge the module via CSS ? 

thank you verry much
bastien

**Comment by bastos5** [comment]
i find everything. You can close
Bastien

**Comment by rondejavu** [comment]
@bastos5 
what you find everything??

**Comment by crimsonclyde** [comment]
Updated mmm-udr.js.
Changed line 20 Module.Register("mmm-udr") to Module.Register("MMM-UDR")
Changed line24 moduleName: "mmm-udr" to "MMM-UDR"
Should work now, thx for the hint!

Cheers clyde

**Comment by crimsonclyde** [comment]
It just doesn't work.
I renamed the project and it works out of the box. :/
You need to use now  "mmm-udr" instead of MMM-UDR
